export const ErrorCodes = {
	// Generics
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	NOT_FOUND: "NOT_FOUND",
	VALIDATION_ERROR: "VALIDATION_ERROR",

	// Auth / Authorization
	AUTH_REQUIRED: "AUTH_REQUIRED",
	FORBIDDEN: "FORBIDDEN",

	// Business
	BUSINESS_NOT_FOUND: "BUSINESS_NOT_FOUND",
	BUSINESS_INACTIVE: "BUSINESS_INACTIVE",
	SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",

	// Service
	SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",
	SERVICE_INACTIVE: "SERVICE_INACTIVE",

	// Schedule
	INVALID_SCHEDULE: "INVALID_SCHEDULE",

	// Appointment
	APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
	APPOINTMENT_ALREADY_CANCELLED: "APPOINTMENT_ALREADY_CANCELLED",
	APPOINTMENT_ALREADY_CONFIRMED: "APPOINTMENT_ALREADY_CONFIRMED",
	APPOINTMENT_TOKEN_INVALID: "APPOINTMENT_TOKEN_INVALID",
	APPOINTMENT_TOKEN_EXPIRED: "APPOINTMENT_TOKEN_EXPIRED",
	APPOINTMENT_NOT_AVAILABLE: "APPOINTMENT_NOT_AVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
